import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import ts from 'typescript';
import OpenCC from 'opencc-js/cn2t';

const root = process.cwd();
const sourceRoot = join(root, 'src');
const output = join(sourceRoot, 'i18n', 'generated', 'zh-TW.ts');
const converter = OpenCC.Converter({ from: 'cn', to: 'tw' });
const sourceCharacters = new Set<string>();
// Single-character conversion is compact, but context-sensitive words and transliterated
// names need a second pass. Entries are expressed as post-character-conversion fixes.
const phraseCorrections = [
  ['關系', '關係'], ['聯系', '聯繫'], ['向往', '嚮往'], ['甲胄', '甲冑'], ['歷法', '曆法'],
  ['幹旱', '乾旱'], ['幹政', '干政'], ['盡快', '儘快'], ['五谷', '五穀'], ['幸存', '倖存'],
  ['巨額', '鉅額'], ['巨款', '鉅款'], ['籤訂', '簽訂'], ['批準', '批准'], ['親徵', '親征'],
  ['赤地千裡', '赤地千里'], ['席卷', '席捲'], ['反復', '反覆'], ['煉金', '鍊金'],
  ['睜只眼', '睜隻眼'], ['借機', '藉機'], ['神跡', '神蹟'], ['穩扎穩打', '穩紮穩打'],
  ['復闢', '復辟'], ['洪水泛濫', '洪水氾濫'], ['河水泛濫', '河水氾濫'], ['復蘇', '復甦'],
  ['古跡', '古蹟'], ['遺跡', '遺蹟'], ['遠徵', '遠征'], ['兼並', '兼併'], ['動蕩', '動盪'],
  ['鐵制', '鐵製'], ['匯編', '彙編'], ['千裡', '千里'], ['萬裡', '萬里'],
  ['戴克裡', '戴克里'], ['亞拉裡克', '亞拉里克'], ['埃特魯裡亞', '埃特魯里亞'],
  ['翁布裡亞', '翁布里亞'], ['亞得裡亞海', '亞得里亞海'], ['諾裡庫姆', '諾里庫姆'],
  ['裡海', '里海'], ['毛裡塔尼亞', '毛里塔尼亞'], ['西西裡', '西西里'],
  ['伊特魯裡亞', '伊特魯里亞'], ['卡拉布裡亞', '卡拉布里亞'], ['裡昂', '里昂'],
  ['裡爾', '里爾'], ['瓦西裡', '瓦西里'], ['德米特裡', '德米特里'], ['鮑裡斯', '鮑里斯'],
  ['米特裡達特', '米特里達特'], ['的黎波裡', '的黎波里'], ['伊德裡斯', '伊德里斯'],
  ['索馬裡', '索馬里'], ['阿裡', '阿里'], ['埃裡克', '埃里克'], ['德幹', '德干'],
  ['塔什幹', '塔什干'], ['黨項', '党項'], ['於闐', '于闐'], ['術赤', '朮赤'],
] as const;

function sourceFiles(folder: string): string[] {
  return readdirSync(folder, { withFileTypes: true }).flatMap((entry) => {
    const path = join(folder, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'i18n' || entry.name === '__tests__') return [];
      return sourceFiles(path);
    }
    return /\.(ts|tsx)$/.test(entry.name) && !entry.name.endsWith('.test.ts') ? [path] : [];
  });
}

function collect(file: string): void {
  const text = readFileSync(file, 'utf8');
  const source = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, file.endsWith('x') ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
  function visit(node: ts.Node): void {
    const literal = ts.isStringLiteralLike(node)
      || ts.isNoSubstitutionTemplateLiteral(node)
      || ts.isTemplateHead(node)
      || ts.isTemplateMiddle(node)
      || ts.isTemplateTail(node)
      ? node.text
      : '';
    if (/[\u3400-\u9fff]/.test(literal)) {
      for (const character of literal) if (/[\u3400-\u9fff]/.test(character)) sourceCharacters.add(character);
    }
    ts.forEachChild(node, visit);
  }
  visit(source);
}

[
  join(sourceRoot, 'App.tsx'),
  ...['components', 'data', 'screens', 'gameplay', 'store'].flatMap((folder) => sourceFiles(join(sourceRoot, folder))),
].forEach(collect);
const generated = [...sourceCharacters]
  .map((character) => [character, converter(character)] as const)
  .filter(([source, target]) => source !== target)
  .sort(([a], [b]) => a.localeCompare(b, 'zh-CN'));
const source = generated.map(([character]) => character).join('');
const target = generated.map(([, character]) => character).join('');
const phraseSource = phraseCorrections.map(([value]) => value).join('|');
const phraseTarget = phraseCorrections.map(([, value]) => value).join('|');
mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, `// Generated by scripts/generate-zh-tw-catalog.ts. Do not edit by hand.
const sourceCharacters = ${JSON.stringify(source)};
const targetCharacters = ${JSON.stringify(target)};
const phraseSources = ${JSON.stringify(phraseSource)}.split('|');
const phraseTargets = ${JSON.stringify(phraseTarget)}.split('|');

export function toGeneratedTraditional(source: string): string {
  let result = [...source].map((character) => {
    const index = sourceCharacters.indexOf(character);
    return index < 0 ? character : targetCharacters[index];
  }).join('');
  for (let index = 0; index < phraseSources.length; index += 1) {
    result = result.split(phraseSources[index]).join(phraseTargets[index]);
  }
  return result;
}
`, 'utf8');
console.log(`Generated ${generated.length} zh-TW character mappings at ${relative(root, output)}.`);
